version: '3.1'

services:

  db:
    image: mysql
    container_name: league_of_legends_container
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: villalba1password
      MYSQL_DATABASE: league_of_legends
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data: